### ISSUE TITLE
Resources Lab

### ISSUE THREAD

**Issue by irfanelahi-ds** [irfanelahi-ds/SEBC#4]

**Comment by irfanelahi-ds** [comment]
Experienced space limitations because I mounted additional EBS volumed under different mount point other than /. 
As a result, tried running the shell script, after modification, however it failed repeatedly. Shared the details in lab files.

**Comment by mfernest** [comment]
`3_YARNtest.sh.md` - I'm sure you understand the point of asking for a file is not simply to assert that the work I asked to see was done.
